### ISSUE TITLE
Seen unexpected behavior with memory issue when input string length is   >= 1048 char

### ISSUE THREAD

**Issue by nagranjeet** [olofhagsand/cligen#25]
Hi,

I have not seen any issue if input string is small but seen unexpected behavior when taking a input string >= 1024

getting below bt

#0  __GI_raise (sig=sig@entry=6)                                                
    at /usr/src/debug/glibc/2.26-r0/git/sysdeps/unix/sysv/linux/raise.c:51      
#1  0x00000034fca355e5 in __GI_abort ()                                         
    at /usr/src/debug/glibc/2.26-r0/git/stdlib/abort.c:90                       
#2  0x00000034fca74bde in __libc_message (action=action@entry=do_abort,         
    fmt=fmt@entry=0x34fcb744d3 "%s\n")                                  aaaaaaaa
    at /usr/src/debug/glibc/2.26-r0/git/sysdeps/posix/libc_fatal.c:181  aaaaaaaa
#3  0x00000034fca7abaa in malloc_printerr (
    str=str@entry=0x34fcb72628 "corrupted size vs. prev_size")
    at /usr/src/debug/glibc/2.26-r0/git/malloc/malloc.c:5368
#4  0x00000034fca7bcc4 in _int_free (av=av@entry=0x34fcda9c40 <main_arena>, 
    p=<optimized out>, have_lock=have_lock@entry=1)
    at /usr/src/debug/glibc/2.26-r0/git/malloc/malloc.c:4302
#5  0x00000034fca7e222 in _int_realloc (av=av@entry=0x34fcda9c40 <main_arena>, 
    oldp=oldp@entry=0x1163c40, oldsize=oldsize@entry=1056, nb=nb@entry=80)
    at /usr/src/debug/glibc/2.26-r0/git/malloc/malloc.c:4666
#6  0x00000034fca8082b in __GI___libc_realloc (oldmem=0x1163c50, bytes=72)
    at /usr/src/debug/glibc/2.26-r0/git/malloc/malloc.c:3231
#7  0x000000350760837d in pt_realloc (pt=0x729548) at cligen_gen.c:315
#8  0x0000003507609d4c in co_insert (pt=0x729548, co1=0x7209d0)
    at cligen_gen.c:1010
#9  0x0000003507617755 in pt_expand_treeref (h=0x66c8b0, coprev=0x0, 

 
is any restriction on input length ?

Thank

**Comment by nagranjeet** [comment]
Resolved , issue was on my side.
